#!/usr/bin/php -q
<?PHP
/*
 */
?>
<?
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';
ob_implicit_flush(true);
require_once "$docroot/webGui/include/Wrappers.php";
extract(parse_plugin_cfg('dynamix',true));

// add translations
$_SERVER['REQUEST_URI'] = 'plugins';
$login_locale = _var($display,'locale');
require_once "$docroot/webGui/include/Translations.php";

$nchan = $argv[$argc-1] == 'nchan'; // console or nchan output

function write(...$messages){
  global $nchan;
  if ($nchan) {
    $com = curl_init();
    curl_setopt_array($com,[
      CURLOPT_URL => 'http://localhost/pub/plugins?buffer_length=1',
      CURLOPT_UNIX_SOCKET_PATH => '/var/run/nginx.socket',
      CURLOPT_POST => 1,
      CURLOPT_RETURNTRANSFER => true
    ]);
    foreach ($messages as $message) {
      curl_setopt($com, CURLOPT_POSTFIELDS, $message);
      curl_exec($com);
    }
    curl_close($com);
  } else {
    foreach ($messages as $message) echo $message;
  }
}

if (exec("wget --spider --no-check-certificate -nv -T10 -t1 https://www.msftncsi.com/ncsi.txt 2>&1|grep -om1 'OK'")) {
  $check = popen('/usr/local/emhttp/plugins/bobbintb.system.dedupe/scripts/venv/bin/python3 /usr/local/emhttp/plugins/bobbintb.system.dedupe/scripts/main.py 2>&1','r');
  while (!feof($check)) {
    $line = rtrim(fgets($check), "\n");
    //$line = str_replace("\n", "", fgets($check));
	write($line);
  
  }
  pclose($check);
} else {
  write(_("No response, aborting")."!\n");
}
if ($nchan) write('_DONE_','');
?>