#!/bin/sh

case "$1" in
start)
   echo "Starting DeDuper daemon"
   /usr/bin/python3 /usr/local/emhttp/plugins.bobbintb.system/scripts/daemon.py > /dev/null 2>&1 &
   ;;
stop)
   echo "Stopping DeDuper daemon"
   killall -9 daemon.py
   ;;
restart)
   $0 stop
   $0 start
   ;;
*)
   echo "Usage: $0 {start|stop|restart}"
   exit 1
esac

exit 0