name: Package PLG
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    # container: ghcr.io/bobbintb/auto_slack_pack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download UnRAID-Plugin-Generator
        run: |
          sudo apt update -y
          sudo apt install python3 -y
          wget https://github.com/bobbintb/UnRAID-Plugin-Generator/raw/refs/heads/main/upg.py
          wget https://github.com/bobbintb/UnRAID-Plugin-Generator/raw/refs/heads/main/requirements.txt
          pip install --break-system-packages -r requirements.txt
          chmod +x upg.py
      - name: Run UnRAID-Plugin-Generator
        run: |
          python3 ./upg.py
          rm plugin.sh
          ls -ls
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: v${{ env.VERSION }}
      #     make_latest: true
      #     files: |
      #       *.txz
