name: Package PLG
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container: ghcr.io/bobbintb/autoslackpack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Download UnRAID-Plugin-Generator
        run: |
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/plugin.sh
          chmod +x plugin.sh
      - name: Run UnRAID-Plugin-Generator
        run: |
          ./plugin.sh
          rm plugin.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          TAG: ${{ env.TAG }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: test
          make_latest: false
          files: |
            *.txz
            *.plg
