name: Package PLG test
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container: bobbintb/unraid-cicd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download UnRAID-Plugin-Generator
        run: |
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/test.py
          wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/main/requirements.txt
          chmod +x test.py
      - name: Run UnRAID-Plugin-Generator
        run: |
          pip install -r requirements.txt
          ./test.py bobbintb.system.dirt.yaml
          rm test.py requirements.txt
          ls -ls
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: v${{ env.VERSION }}
      #     make_latest: true
      #     files: |
      #       *.txz
