name: test
on:
  workflow_dispatch:
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: bobbintb/unraid-cicd
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        # echo "================================= Updating packages ================================="
        # slackpkg update <<< y
        # slackpkg upgrade-all
    - name: Build
      run: |
        echo "================================= Downloading dependencies ================================="
        wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/refs/heads/main/test.py
        wget https://raw.githubusercontent.com/bobbintb/UnRAID-Plugin-Generator/refs/heads/main/bobbintb.system.dirt.yaml
        pip install requests ruamel.yaml xmltodict
        pwd
        ls -lsa
        python test.py bobbintb.system.dirt.yaml
        
