name: test
on:
  workflow_dispatch:
jobs:
  package_and_update:
    permissions: write-all
    runs-on: ubuntu-latest
    container: ghcr.io/bobbintb/auto_slack_pack
    env:
      name: "bobbintb.system.dedupe"
      author: "bobbintb"
      repo: "UnRAID-DeDuper"
      launch: "Settings/Dedupe"
      pluginURL: "https://raw.githubusercontent.com/&author;/&repo;/master/&name;.plg"
      source: "/boot/config/plugins/&name;/&name;"
      icon: "fa-search-minus"
      min: "6.1.9"
    steps:
      - name: Download
        run: |
          wget https://slackware.uk/slackware/slackware64-current/slackware64/n/openssl-3.4.0-x86_64-1.txz
          wget https://slackware.uk/slackware/slackware64-current/slackware64/n/nghttp3-1.6.0-x86_64-1.txz
          wget https://slackware.uk/slackware/slackware64-current/slackware64/l/icu4c-76.1-x86_64-1.txz
          wget https://slackware.uk/slackware/slackware64-current/slackware64/d/gcc-g++-14.2.0-x86_64-2.txz
          wget https://slackware.uk/slackware/slackware64-current/slackware64/d/gcc-14.2.0-x86_64-2.txz
          ln -s /usr/bin/python3 /usr/bin/python
          npm install nexe
          pwd
